.TH surgemail 1 "August 2025" "SurgeMail Helper 1.14.10"
.SH NAME
surgemail \- SurgeMail Helper CLI
.SH SYNOPSIS
.B surgemail
[\fIOPTIONS\fR] \fICOMMAND\fR
.SH SHORT FLAGS
-s status, -r reload, -u update, -d diagnostics, -v version, -w where, -h help
.SH COMMANDS
status, start, stop, strong_stop, restart, reload, check-update, update,
self_check_update, self_update, diagnostics, version, where, man, help
