.TH surgemail 1 "August 2025" "SurgeMail Helper 1.14.6"
.SH NAME
surgemail \- SurgeMail Helper CLI
.SH SYNOPSIS
.B surgemail
[\fIOPTIONS\fR] \fICOMMAND\fR
.SH COMMANDS
status, start, stop, strong_stop, restart, reload, check_update, update,
self_check_update, self_update, diagnostics, version, where, man, help
.SH OPTIONS
\-s, \-r, \-u, \-d, \-v, \-w, \-h
.SH DESCRIPTION
Drop-in helper for managing and updating SurgeMail and this helper script.
