name: Analyze PowerShell

on:
  push:
    paths:
      - "scripts/*.ps1"
  pull_request:
    paths:
      - "scripts/*.ps1"

jobs:
  pssa:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: Install-Module PSScriptAnalyzer -Force -Scope CurrentUser
      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: Invoke-ScriptAnalyzer -Path scripts/surgemail-helper.ps1 -Recurse -Severity Error,Warning