name: Lint shell script
on:
  push:
    paths: ["scripts/*.sh"]
  pull_request:
    paths: ["scripts/*.sh"]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Lint
        run: shellcheck scripts/surgemail-helper.sh